version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: hari-lms-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hari_lms_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: lms_user
      MYSQL_PASSWORD: lms_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - lms-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot Application
  lms-app:
    build: .
    container_name: hari-lms-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hari_lms_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - JWT_SECRET=mySecretKey12345678901234567890123456789012345678901234567890
      - JWT_EXPIRATION=86400000
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - lms-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Optional: phpMyAdmin for database management (development only)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: hari-lms-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - mysql
    networks:
      - lms-network
    profiles:
      - dev

volumes:
  mysql_data:
    driver: local

networks:
  lms-network:
    driver: bridge