# Application Configuration
spring:
  application:
    name: hari-lms

  # Database Configuration (H2 in-memory for development)
  datasource:
    url: jdbc:postgresql://dpg-d35pnoodl3ps7394qq2g-a.oregon-postgres.render.com:5432/project_db_g14r
    username: project_db_g14r_user
    password: pB67bzy6mslUS36XONC2A3tqKmjvJw4V
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    # defer-datasource-initialization: true

  # SQL Initialization
  # sql:
  #   init:
  #     mode: always
  #     data-locations: classpath:data.sql
  #     continue-on-error: false

  # Thymeleaf Configuration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

  # Static Resources
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        cachecontrol:
          max-age: 3600

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-stacktrace: on_param

# JWT Configuration
jwt:
  secret: "mySecretKey12345678901234567890123456789012345678901234567890"
  expiration: 86400000 # 24 hours in milliseconds

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha

# Logging Configuration
logging:
  level:
    com.hari.lms: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Custom Application Properties
app:
  name: "Hari Learning Management System"
  version: "1.0.0"
  description: "Production-ready LMS with Spring Boot, MySQL, JWT, and Thymeleaf"
  admin:
    default-username: admin
    default-email: admin@harilms.com
    default-password: admin123
